services:
  ollama:
    volumes:
      - ollama:/root/.ollama
      - /Users/keigofukumoto/.ollama/models:/root/.ollama/models:rw
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    deploy:
      resources:
        limits:
          memory: 16g  # メモリを16GBに設定
    networks:
      - docker_default  # ネットワークの指定


  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui-compose
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - docker_default  # ネットワークの指定


volumes:
  ollama: {}
  open-webui: {}

networks:
  docker_default:  # docker_defaultネットワークの定義
